---
rackup: /home/sites/pastatron/config.ru
pid: /home/sites/pastatron/tmp/dicsmethin.pid
group: users
address: 0.0.0.0
timeout: 30
port: 5000
log: /home/sites/pastatron/log/thin.log
max_conns: 1024
max_persistent_conns: 512
environment: development
daemonize: true
chdir: /home/sites/pastatron
